### ISSUE TITLE
ZABBIX 7.0 cannot find CurlHttpRequest

### ISSUE THREAD

**Issue by sivn** [havedill/Zabbix_PowerAutomate#1]
To fix this issue, it can be changed to `var request = new HttpRequest();`

Thank you for your time spend with this issue!

**Comment by havedill** [comment]
Sorry about that, i had that originally and then i guess i overwrote it copying something from my 5.0 version

https://github.com/havedill/Zabbix_PowerAutomate/commit/09dd96a996525fc0e90cc5defaa84d911db33ba4
